version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

networks:
  app-network: